[theme]
base = "light"
primaryColor = "#14b8a6"
backgroundColor = "#f4efe3"
secondaryBackgroundColor = "#fffaf0"
textColor = "#141a16"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
